### ISSUE TITLE
Comparing play-json objects gives no proper diff

### ISSUE THREAD

**Issue by francisdb** [softwaremill/diffx#14]
```scala
 obj("test" -> "test", "test2" -> "test2") should matchTo(
      obj("test" -> "test2")
    )
```

output

<img width="728" alt="image" src="https://user-images.githubusercontent.com/161305/65322087-1f700580-dba6-11e9-8557-59373f2c756e.png">

**Comment by ghostbuster91** [comment]
For a workaround please try:
`implicit val dj: Diff[JsObject] = Diff[Map[String, JsValue]].contramap(_.fields.toMap)`
I will investigate this further.

**Comment by ghostbuster91** [comment]
Ok, so I dig a little bit. 
To me it seems that this is a known problem in magnolia https://github.com/propensive/magnolia/issues/178 
Here is why:
`JsObject` extends from `JsValue` trait. `JsObject` is a case class so the type class for it is derived using magnolia. Inside, `JsObject` has a map - `Map[String,JsValue]`. Creation of `Diff` type class for `Map[K,V]` is implemented in way that it needs a `Diff` type class for `Option[V]`. So in our case in order to create `Diff[Map[String,JsValue]]` we need to create `Diff[Option[JsValue]` first. But as described in magnolia's issue such circle will fail. In our case compilation passes because we have specified a fallback method for magnolia to use `.toString` comparison when it cannot derive proper type class.

**Comment by francisdb** [comment]
Looks like the workaround does not work for:

```scala
arr(obj("name" -> "test")) should matchTo(arr(obj("name2" -> "test")))
```

<img width="669" alt="image" src="https://user-images.githubusercontent.com/161305/65695002-091aeb80-e077-11e9-94c7-490c46efe9c5.png">

**Comment by ghostbuster91** [comment]
I released a new version 0.3.3 with fixed magnolia, so it should now work OTB.

**Comment by ghostbuster91** [comment]
As suspected the first case with a JsObjects works OTB, but for the case with a JsArray it fails to find the proper implicit. Surprisingly deriving the Diff tc for a JsArray before using it fixes the problem.
```
    import play.api.libs.json.Json._

    implicit val a: Diff[JsArray] = Derived[Diff[JsArray]]
    arr(obj("name" -> "test")) should matchTo(arr(obj("name2" -> "test")))
```

**Comment by ghostbuster91** [comment]
Yes, it was caused by magnolia. I've just checked and it worked :)
