### ISSUE TITLE
Supporting full comparison between NonEmptyList

### ISSUE THREAD

**Issue by rlopezlozano** [softwaremill/diffx#46]
Here an example, where I need to include the head as part of the implicit to make it works: 

```scala
import cats.data.NonEmptyList
import com.softwaremill.diffx.scalatest.DiffMatcher
import com.softwaremill.diffx.{Derived, Diff}
import org.scalatest.{FlatSpec, Matchers}

class NonEmptyListDiffxTest extends FlatSpec with Matchers with DiffMatcher {

  case class Person(id: Int, firstName: String, surname: String)

  case class Test(id: Int, people: NonEmptyList[Person])

  val person1 = Person(1, "Anna", "Blue")
  val person2 = Person(2, "Jason", "Red")
  val person3 = Person(3, "Anna", "Blue")

  //  implicit val diffPerson: Diff[Person] = Derived[Diff[Person]].ignore(_.id) It does not work 

  implicit val diffTest: Diff[Test] = Derived[Diff[Test]].ignore(_.id).ignore(_.people.head.id)

  val list: NonEmptyList[Person] = NonEmptyList.of(person1, person2)
  val list2: NonEmptyList[Person] = NonEmptyList.of(person3, person2)

  val test1 = Test(1, list)
  val test2 = Test(2, list2)

  test1 should matchTo(test2)
}
```

**Comment by ghostbuster91** [comment]
Hi,

This is all because the `NonEmptyList` is a case class and that's how magnolia processes it. 

So to fix it all you need is to tell diffix to treat `NonEmptyList` as a collection.
To do that you need to override `Diff` instance for `NonEmptyList` like below:
`implicit def nelDif[T:Diff] : Diff[NonEmptyList[T]] = Diff[List[T]].contramap(_.toList)`

But because of the exporting mechanism, the primary type class is `Derived[Diff]` rather than `Diff` so it need to be lifted as follows:
`  implicit def nelDiff[T: Diff]: Derived[Diff[NonEmptyList[T]]] = Derived(Diff[List[T]].contramap[NonEmptyList[T]](_.toList))`

I will add more info about that to documentation to make it clear. Let me know if that helped :)

**Comment by rlopezlozano** [comment]
BIG Thanks for the explanation! It works with the changes suggested! :)

**Comment by adamw** [comment]
We might want to add a `diffx-cats` integration module which would have `Diff` instances defined for cats datastructures

**Comment by ghostbuster91** [comment]
After some considerations I decided to add a diffx-cats module and improve the documentation on how to override existing instance of TC.
